### ISSUE TITLE
wandb: ERROR Error while calling W&B API: project not found (<Response [404]>) 

### ISSUE THREAD

**Issue by ryqdev** [varun19299/rigl-reproducibility#3]
I met this problem with wandb.
I have created my account in Weights & Biases and put my API key to `wandb_api.key`.

There is a possible solution from [this issue](https://github.com/POSTECH-CVLab/SCNeRF/issues/1).
Therefore, I just removed `entity=cfg.wandb.entity,` here https://github.com/varun19299/rigl-reproducibility/blob/97443beac90e03f899652943594695e5152c2b09/main.py#L211 and it was running successfully.

Is there any better solution?

**Comment by varun19299** [comment]
You may not have access to edit the project (https://wandb.ai/ml-reprod-2020). Please create a new project associated with your W&B account, and use it for `cfg.wandb.entity`.

**Comment by ryqdev** [comment]
> You may not have access to edit the project (https://wandb.ai/ml-reprod-2020). Please create a new project associated with your W&B account, and use it for `cfg.wandb.entity`.

Thanks a lot!
